# permissions for end users to view myapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myapi-viewer-role
rules:
- apiGroups:
  - restapi.jonelledacunha
  resources:
  - myapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - restapi.jonelledacunha
  resources:
  - myapis/status
  verbs:
  - get
